name: hebrewbooks
version: 1.1.0+6
publish_to: none
description: Mobile interface to provide access to HebrewBooks.org
environment: 
  sdk: '>=3.1.0 <4.0.0'
dependencies: 
  device_info_plus: ^11.4.0
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.8
  html: ^0.15.6
  http: ^1.1.0
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.20.2
  material_color_utilities: ^0.11.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^29.2.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.8.2
  webview_flutter_wkwebview: ^3.22.1
dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
  pubspec_dependency_sorter: ^1.0.4
flutter: 
  assets:
    - assets/images/logo.png
  uses-material-design: true
